### ISSUE TITLE
Dana Client Library: Create Order

### ISSUE THREAD

**Issue by ardityawahyu** [kitabisa/sangu-dana#2]
Create DANA client library with Go, for create DANA transaction.

reference:
- https://developers.dana.id/?p=512, the flow (you may read the Guest Checkout for now)
- https://developers.dana.id/?p=23, the API detail
- https://developers.dana.id/?p=361, to see required code definition

Acceptance Criteria:

Similar to sangu-jenius or sangu-linkaja, this card is the starter for sangu-dana.
Create library for function: Create Order

**Comment by hitzam** [comment]
any username/password to access the manual (https://developers.dana.id/) @ardityawahyu ?

**Comment by ardityawahyu** [comment]
user: dev@kitabisa.com
pass: cashless-society
